In [200]:
import numpy as np
from itertools import product
import pandas as pd
import os
import foraging_toolkit as ft
import environments
import simulation
import simulation_old 
import success_metrics
import imp
imp.reload(ft)
imp.reload(simulation)
imp.reload(simulation_old)
imp.reload(environments)
imp.reload(success_metrics)


<module 'success_metrics' from 'c:\\Users\\admin\\Dropbox\\Code\\Basis-code\\new-collaborative-intelligence\\mx_refactored\\success_metrics.py'>

Parameters of the forward model. Specify the parameter values for all the cases you are interested in. 

In [201]:
# Parameters of interest in our communication model 
c_trust = np.array([0, 0.5])
sight_radius = [5]
reward_patch_dim = [1, 4]

# List of all possible combination of parameter values 
param_list = [i for i in product(c_trust, sight_radius, reward_patch_dim)]

print(len(param_list))
print('param_list', param_list)




4
param_list [(0.0, 5, 1), (0.0, 5, 4), (0.5, 5, 1), (0.5, 5, 4)]


Generate a dataframe containing all possible combinations of the parameter values specified above.

In [202]:
#each row of both dataframes corresponds to one experiment.  
#columns are parameters 
metadataDF = pd.DataFrame(param_list)

# success_metricsDF = pd.DataFrame(results)
# allresultsDF = pd.concat([metadataDF, success_metricsDF], axis='columns') # concatenate metadata and results 
metadataDF.columns = ["c_trust", "sight_radius", "reward_patch_dim"] 
metadataDF['sim index'] = np.arange(len(metadataDF)).astype(int)
metadataDF.head()
display(metadataDF)

c_trust  sight_radius  reward_patch_dim  sim index
0      0.0             5                 1          0
1      0.0             5                 4          1
2      0.5             5                 1          2
3      0.5             5                 4          3

In [203]:
# select a specific row of the data frame
ind = 1
row = metadataDF.iloc[[ind]]
print(row)
print(row['c_trust'].iloc[0])
print(row['sight_radius'].iloc[0])
print(row['reward_patch_dim'].iloc[0])

   c_trust  sight_radius  reward_patch_dim  sim index
1      0.0             5                 4          1
0.0
5
4


In [204]:
test_arr = np.zeros((5))
print(test_arr.shape)

(5,)


*Part 2*
Test run one of the simulations from metadata (one row)

In [205]:
nsims = len(metadataDF)
N_frames = 50
N_agents = 9
N_total_food_units = 16
edge_size = 30
N_runs = 100
# nsims = 2 # TEST

# data frame to store all success values across all simulations and runs of each simulation
success_measures_allDF = pd.DataFrame() 
success_sims_list = []

home_dir = "C:\\Basis_data\\" # 

# save metadata to home directory
metadataDF.to_csv(home_dir + '\metadataDF' + '.csv')

for si in range(nsims):
    
    # 1. pull out parameters from row si in the metadata
    df_row = metadataDF.iloc[[si]]
    c_trust = df_row['c_trust'].iloc[0]
    sight_radius = df_row['sight_radius'].iloc[0]
    reward_patch_dim = df_row['reward_patch_dim'].iloc[0].astype(int)

    # print(df_row)
    # print(reward_patch_dim)

    mean_times_to_first_reward = np.zeros((N_runs))
    num_birds_failed = np.zeros((N_runs))

    # Do multiple runs of the simulation and store the results in a results dataframe
    for ri in range(N_runs):
        # 2. Feed the parameters through the run() function once (later we'll do this many times)
        env = environments.Environment(edge_size=edge_size, N_total_food_units=N_total_food_units, patch_dim=reward_patch_dim)
        env.add_food_patches() #food_statistics_type="drop_food_once")
        # sim = simulation_old.Simulation(env, N_agents=N_agents, N_frames=N_frames)
        sim = simulation.SimulateCommunicators(env, N_frames, N_agents, c_trust=c_trust, sight_radius=sight_radius)
        sim.run()
        # print(sim.all_birdsDF)
        # # print(sim.all_rewardsDF) 
        # # by this point we should have birdlocsDF and rewardlocsDF 
        

        # # # 3. Compute success measures 
        
        time_to_first_allbirds = np.zeros(N_agents)
        for bird_id in range(1, N_agents + 1):
            singlebirdDF = sim.all_birdsDF.loc[sim.all_birdsDF['bird'] == bird_id]  
            time_to_first_allbirds[bird_id - 1] = success_metrics.compute_time_to_first_reward(singlebirdDF, sim.all_rewardsDF, N_frames)
            
        # these are the success measures
        mean_times_to_first_reward[ri] = np.mean(time_to_first_allbirds) # take the average across birds
        num_birds_failed[ri] = np.sum(time_to_first_allbirds < 0) # number of birds that failed to reach food
        # print(num_birds_failed)
        #

        # SAVE THE RAW DATA 
        # make a new folder  
        sim_folder = 'sim' + str(si) + '_run' + str(ri)
        sim_dir = home_dir + sim_folder
        if not os.path.isdir(sim_dir):
            os.makedirs(sim_dir)
            print("Directory %s was created." %sim_folder)

        birdfile = '\\birdlocsDF'
        rewardfile = '\\rewardlocsDF'
        sim.all_birdsDF.to_csv(sim_dir + birdfile + ".csv")
        sim.all_rewardsDF.to_csv(sim_dir + rewardfile + ".csv")

       

    #4. Combine the metadata and the success measures into the results dataframe 
        # create a new row in the results data frame, then concatenate 
    success_measures_onesim_DF = pd.DataFrame(
        {
            "run index": np.arange(N_runs),
            "time to first food": mean_times_to_first_reward,
            "num birds failed": num_birds_failed,
        }
    )

    success_sims_list.append(success_measures_onesim_DF)

success_measures_allDF = pd.concat(success_sims_list)

    # 5. Save the raw data into a separate folder.


print(len(success_sims_list))
print(len(mean_times_to_first_reward))
print(len(success_measures_onesim_DF))
print(display(success_measures_onesim_DF))
print(display(success_measures_allDF))

# Concatenate metadataDF and success_measures_allDF into a new dataframe called resultsDF

    
# Save the results dataframe into the same folder as the metadata


Directory sim0_run0 was created.
Directory sim0_run1 was created.
Directory sim0_run2 was created.
Directory sim0_run3 was created.
Directory sim0_run4 was created.
Directory sim0_run5 was created.
Directory sim0_run6 was created.
Directory sim0_run7 was created.
Directory sim0_run8 was created.
Directory sim0_run9 was created.
Directory sim0_run10 was created.
Directory sim0_run11 was created.
Directory sim0_run12 was created.
Directory sim0_run13 was created.
Directory sim0_run14 was created.
Directory sim0_run15 was created.
Directory sim0_run16 was created.
Directory sim0_run17 was created.
Directory sim0_run18 was created.
Directory sim0_run19 was created.
Directory sim0_run20 was created.
Directory sim0_run21 was created.
Directory sim0_run22 was created.
Directory sim0_run23 was created.
Directory sim0_run24 was created.
Directory sim0_run25 was created.
Directory sim0_run26 was created.
Directory sim0_run27 was created.
Directory sim0_run28 was created.
Directory sim0_run29 was

run index  time to first food  num birds failed
0           0           -0.222222               8.0
1           1            5.333333               3.0
2           2            0.777778               7.0
3           3            8.444444               3.0
4           4            5.444444               2.0
..        ...                 ...               ...
95         95            4.777778               5.0
96         96            3.777778               1.0
97         97            2.555556               6.0
98         98            5.111111               7.0
99         99            1.333333               7.0

[100 rows x 3 columns]

None


run index  time to first food  num birds failed
0           0            2.111111               0.0
1           1            7.111111               0.0
2           2            1.333333               0.0
3           3            1.444444               0.0
4           4            2.000000               0.0
..        ...                 ...               ...
95         95            4.777778               5.0
96         96            3.777778               1.0
97         97            2.555556               6.0
98         98            5.111111               7.0
99         99            1.333333               7.0

[400 rows x 3 columns]

None


In [206]:
# Concatenate metadataDF and success_measures_allDF into a new dataframe called resultsDF

# First, duplicate each row (sim) of metadataDF by the number of runs
newDF = pd.DataFrame(np.repeat(metadataDF.values, N_runs, axis=0))
newDF.columns = metadataDF.columns
print(newDF)




     c_trust  sight_radius  reward_patch_dim  sim index
0        0.0           5.0               1.0        0.0
1        0.0           5.0               1.0        0.0
2        0.0           5.0               1.0        0.0
3        0.0           5.0               1.0        0.0
4        0.0           5.0               1.0        0.0
..       ...           ...               ...        ...
395      0.5           5.0               4.0        3.0
396      0.5           5.0               4.0        3.0
397      0.5           5.0               4.0        3.0
398      0.5           5.0               4.0        3.0
399      0.5           5.0               4.0        3.0

[400 rows x 4 columns]


In [207]:
# change the indexing of the rows of this dataframe so we can concatenate with metadataDF
successDF = success_measures_allDF.reset_index(drop=True)
display(successDF)

run index  time to first food  num birds failed
0            0            2.111111               0.0
1            1            7.111111               0.0
2            2            1.333333               0.0
3            3            1.444444               0.0
4            4            2.000000               0.0
..         ...                 ...               ...
395         95            4.777778               5.0
396         96            3.777778               1.0
397         97            2.555556               6.0
398         98            5.111111               7.0
399         99            1.333333               7.0

[400 rows x 3 columns]

In [208]:
# Concatenate metadataDF and 
allresultsDF = pd.concat([newDF, successDF], axis=1)
display(allresultsDF)

c_trust  sight_radius  reward_patch_dim  sim index  run index  \
0        0.0           5.0               1.0        0.0          0   
1        0.0           5.0               1.0        0.0          1   
2        0.0           5.0               1.0        0.0          2   
3        0.0           5.0               1.0        0.0          3   
4        0.0           5.0               1.0        0.0          4   
..       ...           ...               ...        ...        ...   
395      0.5           5.0               4.0        3.0         95   
396      0.5           5.0               4.0        3.0         96   
397      0.5           5.0               4.0        3.0         97   
398      0.5           5.0               4.0        3.0         98   
399      0.5           5.0               4.0        3.0         99   

     time to first food  num birds failed  
0              2.111111               0.0  
1              7.111111               0.0  
2              1.333333               0.0  
3              1.444444               0.0  
4              2.000000               0.0  
..                  ...               ...  
395            4.777778               5.0  
396            3.777778               1.0  
397            2.555556               6.0  
398            5.111111               7.0  
399            1.333333               7.0  

[400 rows x 7 columns]

*Save data in a folder*


In [209]:
# save metadata to home directory
allresultsDF.to_csv(home_dir + 'resultsDF' + '.csv')

Test one of the simulations by animating it.

In [210]:
communicators = ft.object_from_data(sim.all_birdsDF, sim.all_rewardsDF)
ft.animate_birds(communicators, plot_rewards=True,
                  width = 600, height = 600, point_size = 10)

In [211]:
print(sim.all_birdsDF.loc[sim.all_birdsDF['bird'] == 1])

       x     y  time  bird           type
0   22.0  18.0     1     1  communicators
1   25.0  18.0     2     1  communicators
2   24.0  16.0     3     1  communicators
3   24.0  17.0     4     1  communicators
4   22.0  17.0     5     1  communicators
5   21.0  17.0     6     1  communicators
6   18.0  17.0     7     1  communicators
7   16.0  18.0     8     1  communicators
8   15.0  19.0     9     1  communicators
9   16.0  20.0    10     1  communicators
10  17.0  21.0    11     1  communicators
11  18.0  20.0    12     1  communicators
12  21.0  20.0    13     1  communicators
13  19.0  21.0    14     1  communicators
14  18.0  20.0    15     1  communicators
15  16.0  19.0    16     1  communicators
16  14.0  21.0    17     1  communicators
17  12.0  23.0    18     1  communicators
18  11.0  25.0    19     1  communicators
19  11.0  25.0    20     1  communicators
20  11.0  25.0    21     1  communicators
21  11.0  25.0    22     1  communicators
22  11.0  25.0    23     1  commun

In [212]:
# print(sim.all_rewardsDF[]) 
print(sim.all_rewardsDF.loc[sim.all_rewardsDF['time'] == 4])


     x   y  time
0    9  25     4
1   10  25     4
2   11  25     4
3   12  25     4
4    9  26     4
5   10  26     4
6   11  26     4
7   12  26     4
8    9  27     4
9   10  27     4
10  11  27     4
11  12  27     4
12   9  28     4
13  10  28     4
14  11  28     4
15  12  28     4


In [213]:

time_to_first_allbirds = np.zeros(N_agents)
# print(time_to_first_allbirds.shape)

for bird_id in range(1, N_agents + 1):
    # bird_id = 2
    singlebirdDF = sim.all_birdsDF.loc[sim.all_birdsDF['bird'] == bird_id] 
    display(singlebirdDF)
    time_to_first_allbirds[bird_id - 1] = success_metrics.compute_time_to_first_reward(singlebirdDF, sim.all_rewardsDF, N_frames)

    print(time_to_first_allbirds)

num_birds_failed = np.sum(time_to_first_allbirds < 0)
print('Num birds failed to find food = ' + str(num_birds_failed))


x     y  time  bird           type
0   22.0  18.0     1     1  communicators
1   25.0  18.0     2     1  communicators
2   24.0  16.0     3     1  communicators
3   24.0  17.0     4     1  communicators
4   22.0  17.0     5     1  communicators
5   21.0  17.0     6     1  communicators
6   18.0  17.0     7     1  communicators
7   16.0  18.0     8     1  communicators
8   15.0  19.0     9     1  communicators
9   16.0  20.0    10     1  communicators
10  17.0  21.0    11     1  communicators
11  18.0  20.0    12     1  communicators
12  21.0  20.0    13     1  communicators
13  19.0  21.0    14     1  communicators
14  18.0  20.0    15     1  communicators
15  16.0  19.0    16     1  communicators
16  14.0  21.0    17     1  communicators
17  12.0  23.0    18     1  communicators
18  11.0  25.0    19     1  communicators
19  11.0  25.0    20     1  communicators
20  11.0  25.0    21     1  communicators
21  11.0  25.0    22     1  communicators
22  11.0  25.0    23     1  communicators
23  11.0  25.0    24     1  communicators
24  11.0  25.0    25     1  communicators
25  11.0  25.0    26     1  communicators
26  11.0  25.0    27     1  communicators
27  11.0  25.0    28     1  communicators
28  11.0  25.0    29     1  communicators
29  11.0  25.0    30     1  communicators
30  11.0  25.0    31     1  communicators
31  11.0  25.0    32     1  communicators
32  11.0  25.0    33     1  communicators
33  11.0  25.0    34     1  communicators
34  11.0  25.0    35     1  communicators
35  11.0  25.0    36     1  communicators
36  11.0  25.0    37     1  communicators
37  11.0  25.0    38     1  communicators
38  11.0  25.0    39     1  communicators
39  11.0  25.0    40     1  communicators
40  11.0  25.0    41     1  communicators
41  11.0  25.0    42     1  communicators
42  11.0  25.0    43     1  communicators
43  11.0  25.0    44     1  communicators
44  11.0  25.0    45     1  communicators
45  11.0  25.0    46     1  communicators
46  11.0  25.0    47     1  communicators
47  11.0  25.0    48     1  communicators
48  11.0  25.0    49     1  communicators
49   0.0   0.0    50     1  communicators

[18.  0.  0.  0.  0.  0.  0.  0.  0.]


x     y  time  bird           type
0   1.0  10.0     1     2  communicators
1   1.0   9.0     2     2  communicators
2   0.0   7.0     3     2  communicators
3   2.0   9.0     4     2  communicators
4   1.0  10.0     5     2  communicators
5   3.0   8.0     6     2  communicators
6   1.0  10.0     7     2  communicators
7   0.0   9.0     8     2  communicators
8   2.0  11.0     9     2  communicators
9   0.0  12.0    10     2  communicators
10  1.0  14.0    11     2  communicators
11  2.0  12.0    12     2  communicators
12  1.0  13.0    13     2  communicators
13  0.0  12.0    14     2  communicators
14  1.0  11.0    15     2  communicators
15  2.0  13.0    16     2  communicators
16  4.0  12.0    17     2  communicators
17  2.0  13.0    18     2  communicators
18  2.0  15.0    19     2  communicators
19  1.0  13.0    20     2  communicators
20  0.0  15.0    21     2  communicators
21  2.0  16.0    22     2  communicators
22  2.0  13.0    23     2  communicators
23  2.0  15.0    24     2  communicators
24  4.0  15.0    25     2  communicators
25  3.0  15.0    26     2  communicators
26  1.0  13.0    27     2  communicators
27  2.0  15.0    28     2  communicators
28  2.0  12.0    29     2  communicators
29  4.0  13.0    30     2  communicators
30  2.0  11.0    31     2  communicators
31  2.0  11.0    32     2  communicators
32  4.0  10.0    33     2  communicators
33  4.0  11.0    34     2  communicators
34  3.0   9.0    35     2  communicators
35  1.0   9.0    36     2  communicators
36  2.0  10.0    37     2  communicators
37  3.0  11.0    38     2  communicators
38  5.0  12.0    39     2  communicators
39  4.0  12.0    40     2  communicators
40  4.0  13.0    41     2  communicators
41  5.0  15.0    42     2  communicators
42  7.0  14.0    43     2  communicators
43  4.0  14.0    44     2  communicators
44  6.0  16.0    45     2  communicators
45  4.0  16.0    46     2  communicators
46  5.0  18.0    47     2  communicators
47  5.0  17.0    48     2  communicators
48  5.0  20.0    49     2  communicators
49  0.0   0.0    50     2  communicators

[18. -1.  0.  0.  0.  0.  0.  0.  0.]


x     y  time  bird           type
0   29.0  24.0     1     3  communicators
1   27.0  25.0     2     3  communicators
2   28.0  24.0     3     3  communicators
3   26.0  23.0     4     3  communicators
4   27.0  22.0     5     3  communicators
5   26.0  23.0     6     3  communicators
6   27.0  25.0     7     3  communicators
7   26.0  25.0     8     3  communicators
8   26.0  26.0     9     3  communicators
9   25.0  27.0    10     3  communicators
10  26.0  25.0    11     3  communicators
11  27.0  24.0    12     3  communicators
12  25.0  23.0    13     3  communicators
13  23.0  25.0    14     3  communicators
14  21.0  23.0    15     3  communicators
15  23.0  21.0    16     3  communicators
16  23.0  22.0    17     3  communicators
17  21.0  22.0    18     3  communicators
18  21.0  24.0    19     3  communicators
19  23.0  26.0    20     3  communicators
20  26.0  26.0    21     3  communicators
21  24.0  28.0    22     3  communicators
22  24.0  28.0    23     3  communicators
23  21.0  28.0    24     3  communicators
24  21.0  25.0    25     3  communicators
25  19.0  24.0    26     3  communicators
26  16.0  24.0    27     3  communicators
27  14.0  25.0    28     3  communicators
28  11.0  25.0    29     3  communicators
29  11.0  25.0    30     3  communicators
30  11.0  25.0    31     3  communicators
31  11.0  25.0    32     3  communicators
32  11.0  25.0    33     3  communicators
33  11.0  25.0    34     3  communicators
34  11.0  25.0    35     3  communicators
35  11.0  25.0    36     3  communicators
36  11.0  25.0    37     3  communicators
37  11.0  25.0    38     3  communicators
38  11.0  25.0    39     3  communicators
39  11.0  25.0    40     3  communicators
40  11.0  25.0    41     3  communicators
41  11.0  25.0    42     3  communicators
42  11.0  25.0    43     3  communicators
43  11.0  25.0    44     3  communicators
44  11.0  25.0    45     3  communicators
45  11.0  25.0    46     3  communicators
46  11.0  25.0    47     3  communicators
47  11.0  25.0    48     3  communicators
48  11.0  25.0    49     3  communicators
49   0.0   0.0    50     3  communicators

[18. -1. -1.  0.  0.  0.  0.  0.  0.]


x     y  time  bird           type
0   29.0  16.0     1     4  communicators
1   27.0  15.0     2     4  communicators
2   26.0  17.0     3     4  communicators
3   24.0  16.0     4     4  communicators
4   22.0  15.0     5     4  communicators
5   22.0  18.0     6     4  communicators
6   20.0  16.0     7     4  communicators
7   22.0  15.0     8     4  communicators
8   22.0  17.0     9     4  communicators
9   25.0  17.0    10     4  communicators
10  25.0  18.0    11     4  communicators
11  24.0  18.0    12     4  communicators
12  24.0  19.0    13     4  communicators
13  26.0  19.0    14     4  communicators
14  28.0  21.0    15     4  communicators
15  28.0  18.0    16     4  communicators
16  27.0  16.0    17     4  communicators
17  29.0  15.0    18     4  communicators
18  28.0  17.0    19     4  communicators
19  25.0  17.0    20     4  communicators
20  25.0  15.0    21     4  communicators
21  23.0  15.0    22     4  communicators
22  24.0  13.0    23     4  communicators
23  24.0  13.0    24     4  communicators
24  22.0  13.0    25     4  communicators
25  21.0  11.0    26     4  communicators
26  22.0   9.0    27     4  communicators
27  19.0   9.0    28     4  communicators
28  18.0   9.0    29     4  communicators
29  20.0  11.0    30     4  communicators
30  21.0  12.0    31     4  communicators
31  22.0  13.0    32     4  communicators
32  20.0  15.0    33     4  communicators
33  21.0  16.0    34     4  communicators
34  19.0  15.0    35     4  communicators
35  19.0  17.0    36     4  communicators
36  17.0  18.0    37     4  communicators
37  15.0  19.0    38     4  communicators
38  13.0  21.0    39     4  communicators
39  12.0  23.0    40     4  communicators
40  11.0  25.0    41     4  communicators
41  11.0  25.0    42     4  communicators
42  11.0  25.0    43     4  communicators
43  11.0  25.0    44     4  communicators
44  11.0  25.0    45     4  communicators
45  11.0  25.0    46     4  communicators
46  11.0  25.0    47     4  communicators
47  11.0  25.0    48     4  communicators
48  11.0  25.0    49     4  communicators
49   0.0   0.0    50     4  communicators

[18. -1. -1. -1.  0.  0.  0.  0.  0.]


x     y  time  bird           type
0   17.0   9.0     1     5  communicators
1   16.0  10.0     2     5  communicators
2   18.0   9.0     3     5  communicators
3   17.0   9.0     4     5  communicators
4   18.0  11.0     5     5  communicators
5   18.0  10.0     6     5  communicators
6   21.0  10.0     7     5  communicators
7   20.0   9.0     8     5  communicators
8   22.0  10.0     9     5  communicators
9   21.0  11.0    10     5  communicators
10  20.0  10.0    11     5  communicators
11  22.0  12.0    12     5  communicators
12  20.0  13.0    13     5  communicators
13  19.0  12.0    14     5  communicators
14  17.0  12.0    15     5  communicators
15  17.0  13.0    16     5  communicators
16  16.0  13.0    17     5  communicators
17  17.0  13.0    18     5  communicators
18  19.0  14.0    19     5  communicators
19  16.0  14.0    20     5  communicators
20  16.0  16.0    21     5  communicators
21  16.0  14.0    22     5  communicators
22  14.0  14.0    23     5  communicators
23  16.0  16.0    24     5  communicators
24  15.0  16.0    25     5  communicators
25  13.0  18.0    26     5  communicators
26  13.0  21.0    27     5  communicators
27  11.0  23.0    28     5  communicators
28  11.0  25.0    29     5  communicators
29  11.0  25.0    30     5  communicators
30  11.0  25.0    31     5  communicators
31  11.0  25.0    32     5  communicators
32  11.0  25.0    33     5  communicators
33  11.0  25.0    34     5  communicators
34  11.0  25.0    35     5  communicators
35  11.0  25.0    36     5  communicators
36  11.0  25.0    37     5  communicators
37  11.0  25.0    38     5  communicators
38  11.0  25.0    39     5  communicators
39  11.0  25.0    40     5  communicators
40  11.0  25.0    41     5  communicators
41  11.0  25.0    42     5  communicators
42  11.0  25.0    43     5  communicators
43  11.0  25.0    44     5  communicators
44  11.0  25.0    45     5  communicators
45  11.0  25.0    46     5  communicators
46  11.0  25.0    47     5  communicators
47  11.0  25.0    48     5  communicators
48  11.0  25.0    49     5  communicators
49   0.0   0.0    50     5  communicators

[18. -1. -1. -1. -1.  0.  0.  0.  0.]


x     y  time  bird           type
0    6.0   2.0     1     6  communicators
1    8.0   3.0     2     6  communicators
2   11.0   3.0     3     6  communicators
3    9.0   2.0     4     6  communicators
4   11.0   0.0     5     6  communicators
5   14.0   0.0     6     6  communicators
6   12.0   2.0     7     6  communicators
7   14.0   0.0     8     6  communicators
8   14.0   0.0     9     6  communicators
9   12.0   2.0    10     6  communicators
10  10.0   0.0    11     6  communicators
11   9.0   0.0    12     6  communicators
12   9.0   2.0    13     6  communicators
13   7.0   4.0    14     6  communicators
14   6.0   6.0    15     6  communicators
15   5.0   5.0    16     6  communicators
16   6.0   3.0    17     6  communicators
17   8.0   2.0    18     6  communicators
18   6.0   4.0    19     6  communicators
19   5.0   3.0    20     6  communicators
20   3.0   2.0    21     6  communicators
21   3.0   2.0    22     6  communicators
22   1.0   3.0    23     6  communicators
23   2.0   4.0    24     6  communicators
24   2.0   4.0    25     6  communicators
25   2.0   7.0    26     6  communicators
26   2.0   9.0    27     6  communicators
27   2.0  12.0    28     6  communicators
28   3.0  14.0    29     6  communicators
29   3.0  16.0    30     6  communicators
30   5.0  14.0    31     6  communicators
31   7.0  12.0    32     6  communicators
32   8.0  11.0    33     6  communicators
33  10.0  12.0    34     6  communicators
34  11.0  10.0    35     6  communicators
35  11.0  12.0    36     6  communicators
36  11.0  15.0    37     6  communicators
37  13.0  17.0    38     6  communicators
38  14.0  19.0    39     6  communicators
39  12.0  21.0    40     6  communicators
40  12.0  24.0    41     6  communicators
41  11.0  25.0    42     6  communicators
42  11.0  25.0    43     6  communicators
43  11.0  25.0    44     6  communicators
44  11.0  25.0    45     6  communicators
45  11.0  25.0    46     6  communicators
46  11.0  25.0    47     6  communicators
47  11.0  25.0    48     6  communicators
48  11.0  25.0    49     6  communicators
49   0.0   0.0    50     6  communicators

[18. -1. -1. -1. -1. -1.  0.  0.  0.]


x     y  time  bird           type
0   10.0  29.0     1     7  communicators
1   11.0  27.0     2     7  communicators
2   10.0  27.0     3     7  communicators
3   11.0  27.0     4     7  communicators
4   11.0  26.0     5     7  communicators
5   11.0  27.0     6     7  communicators
6   10.0  27.0     7     7  communicators
7   11.0  27.0     8     7  communicators
8   10.0  27.0     9     7  communicators
9   10.0  27.0    10     7  communicators
10  10.0  27.0    11     7  communicators
11  10.0  27.0    12     7  communicators
12  11.0  27.0    13     7  communicators
13  10.0  27.0    14     7  communicators
14  11.0  27.0    15     7  communicators
15  11.0  27.0    16     7  communicators
16  11.0  27.0    17     7  communicators
17  10.0  27.0    18     7  communicators
18  11.0  25.0    19     7  communicators
19  11.0  25.0    20     7  communicators
20  11.0  25.0    21     7  communicators
21  11.0  25.0    22     7  communicators
22  11.0  25.0    23     7  communicators
23  11.0  25.0    24     7  communicators
24  11.0  25.0    25     7  communicators
25  11.0  25.0    26     7  communicators
26  11.0  25.0    27     7  communicators
27  11.0  25.0    28     7  communicators
28  11.0  25.0    29     7  communicators
29  11.0  25.0    30     7  communicators
30  11.0  25.0    31     7  communicators
31  11.0  25.0    32     7  communicators
32  11.0  25.0    33     7  communicators
33  11.0  25.0    34     7  communicators
34  11.0  25.0    35     7  communicators
35  11.0  25.0    36     7  communicators
36  11.0  25.0    37     7  communicators
37  11.0  25.0    38     7  communicators
38  11.0  25.0    39     7  communicators
39  11.0  25.0    40     7  communicators
40  11.0  25.0    41     7  communicators
41  11.0  25.0    42     7  communicators
42  11.0  25.0    43     7  communicators
43  11.0  25.0    44     7  communicators
44  11.0  25.0    45     7  communicators
45  11.0  25.0    46     7  communicators
46  11.0  25.0    47     7  communicators
47  11.0  25.0    48     7  communicators
48  11.0  25.0    49     7  communicators
49   0.0   0.0    50     7  communicators

[18. -1. -1. -1. -1. -1.  1.  0.  0.]


x     y  time  bird           type
0   16.0   4.0     1     8  communicators
1   17.0   3.0     2     8  communicators
2   15.0   5.0     3     8  communicators
3   17.0   5.0     4     8  communicators
4   18.0   5.0     5     8  communicators
5   20.0   7.0     6     8  communicators
6   20.0   5.0     7     8  communicators
7   19.0   5.0     8     8  communicators
8   17.0   3.0     9     8  communicators
9   16.0   5.0    10     8  communicators
10  17.0   4.0    11     8  communicators
11  15.0   3.0    12     8  communicators
12  16.0   2.0    13     8  communicators
13  16.0   3.0    14     8  communicators
14  18.0   2.0    15     8  communicators
15  19.0   1.0    16     8  communicators
16  17.0   3.0    17     8  communicators
17  18.0   3.0    18     8  communicators
18  19.0   4.0    19     8  communicators
19  18.0   3.0    20     8  communicators
20  18.0   5.0    21     8  communicators
21  17.0   7.0    22     8  communicators
22  15.0   7.0    23     8  communicators
23  14.0   8.0    24     8  communicators
24  12.0   6.0    25     8  communicators
25  15.0   6.0    26     8  communicators
26  12.0   6.0    27     8  communicators
27  15.0   6.0    28     8  communicators
28  15.0   6.0    29     8  communicators
29  16.0   6.0    30     8  communicators
30  14.0   7.0    31     8  communicators
31  14.0   5.0    32     8  communicators
32  14.0   7.0    33     8  communicators
33  13.0   9.0    34     8  communicators
34  13.0   6.0    35     8  communicators
35  13.0   9.0    36     8  communicators
36  13.0  12.0    37     8  communicators
37  11.0  12.0    38     8  communicators
38  12.0  14.0    39     8  communicators
39  11.0  13.0    40     8  communicators
40  13.0  15.0    41     8  communicators
41  13.0  16.0    42     8  communicators
42  13.0  19.0    43     8  communicators
43  13.0  22.0    44     8  communicators
44  11.0  24.0    45     8  communicators
45  11.0  25.0    46     8  communicators
46  11.0  25.0    47     8  communicators
47  11.0  25.0    48     8  communicators
48  11.0  25.0    49     8  communicators
49   0.0   0.0    50     8  communicators

[18. -1. -1. -1. -1. -1.  1. -1.  0.]


x     y  time  bird           type
0   11.0  12.0     1     9  communicators
1   13.0  13.0     2     9  communicators
2   15.0  13.0     3     9  communicators
3   16.0  14.0     4     9  communicators
4   16.0  16.0     5     9  communicators
5   19.0  16.0     6     9  communicators
6   18.0  16.0     7     9  communicators
7   17.0  18.0     8     9  communicators
8   19.0  16.0     9     9  communicators
9   19.0  15.0    10     9  communicators
10  17.0  17.0    11     9  communicators
11  15.0  19.0    12     9  communicators
12  17.0  19.0    13     9  communicators
13  18.0  21.0    14     9  communicators
14  18.0  24.0    15     9  communicators
15  20.0  25.0    16     9  communicators
16  20.0  27.0    17     9  communicators
17  22.0  26.0    18     9  communicators
18  23.0  27.0    19     9  communicators
19  20.0  27.0    20     9  communicators
20  18.0  29.0    21     9  communicators
21  20.0  28.0    22     9  communicators
22  18.0  26.0    23     9  communicators
23  16.0  27.0    24     9  communicators
24  13.0  27.0    25     9  communicators
25  11.0  25.0    26     9  communicators
26  11.0  25.0    27     9  communicators
27  11.0  25.0    28     9  communicators
28  11.0  25.0    29     9  communicators
29  11.0  25.0    30     9  communicators
30  11.0  25.0    31     9  communicators
31  11.0  25.0    32     9  communicators
32  11.0  25.0    33     9  communicators
33  11.0  25.0    34     9  communicators
34  11.0  25.0    35     9  communicators
35  11.0  25.0    36     9  communicators
36  11.0  25.0    37     9  communicators
37  11.0  25.0    38     9  communicators
38  11.0  25.0    39     9  communicators
39  11.0  25.0    40     9  communicators
40  11.0  25.0    41     9  communicators
41  11.0  25.0    42     9  communicators
42  11.0  25.0    43     9  communicators
43  11.0  25.0    44     9  communicators
44  11.0  25.0    45     9  communicators
45  11.0  25.0    46     9  communicators
46  11.0  25.0    47     9  communicators
47  11.0  25.0    48     9  communicators
48  11.0  25.0    49     9  communicators
49   0.0   0.0    50     9  communicators

[18. -1. -1. -1. -1. -1.  1. -1. -1.]
Num birds failed to find food = 7
